version: '2'
services:
  play:
    build: .
    environment:
      TZ: Asia/Tokyo
      APP_ENV: docker
    volumes:
      - .:/root
    ports:
      - 9000:9000
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: play
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
